const data = [
  {
    id: 1,
    img: "./img/Gods/neith.png",
    nameItem: "Neith",
    description:"Tecelã do Destino",
    value: "Caçador",
    addCart: "Atirador",
    class: "./img/icons/caçador.png",
    type: "Físico",
  },
  {
    id: 2,
    img: "./img/Gods/anubis.png",
    nameItem: "Anúbis",
    description: "Deus dos Mortos",
    value: "Mago",
    addCart: "Atirador",
    class: "./img/icons/mago.png",
    type: "Mágico",
  },
  {
    id: 3,
    img: "./img/Gods/cila.png",
    nameItem: "Cila",
    description: "Horror das Profundezas",
    value: "Mago",
    addCart: "Atirador",
    class: "./img/icons/mago.png",
    type: "Mágico",
  },
  {
    id: 4,
    img: "./img/Gods/kukulkan.png",
    nameItem: "Kukulkan",
    description: "Serpente dos Nove Ventos",
    value: "Mago",
    addCart: "Atirador",
    class: "./img/icons/mago.png",
    type: "Mágico",
  }, 
  {
    id: 5,
    img: "./img/Gods/chac.png",
    nameItem: "Chaac",
    description:
      "Deus da Chuva",
    value: "Guerreiro",
    addCart: "Adicionar ao carrinho",
    class: "./img/icons/guerreiro.png",
    type: "Físico",
  },
  {
    id: 6,
    img: "./img/Gods/cupido.png",
    nameItem: "Cupido",
    description:
      "Deus do Amor",
    value: "Caçador",
    addCart: "Atirador",
    class: "./img/icons/caçador.png",
    type: "Físico",
  },
  {
    id: 7,
    img: "./img/Gods/izanami.png",
    nameItem: "Izanami",
    description:
      "Matriarca da Morte",
    value: "Caçador",
    addCart: "Atirador",
    class: "./img/icons/caçador.png",
    type: "Físico",
  },
  {
    id: 8,
    img: "./img/Gods/thanatos.png",
    nameItem: "Thanatos",
    description:
      "O Punho da Morte",
    value: "Assassino",
    addCart: "Corporal",
    class: "./img/icons/assassino.png",
    type: "Físico",
  },
  {
    id: 9,
    img: "./img/Gods/ymir.png",
    nameItem: "Ymir",
    description: "O Pai dos Gigantes de Gelo",
    value: "Guardião",
    addCart: "Corporal",
    class: "./img/icons/guardiao.png",
    type: "Mágico",
  },
  {
    id: 10,
    img: "./img/Gods/baco.png",
    nameItem: "Baco",
    description: "Deus do vinho",
    value: "Guardião",
    addCart: "Corporal",
    class: "./img/icons/guardiao.png",
    type: "Mágico",
  },
  {
    id: 11,
    img: "./img/Gods/sun wukong.png",
    nameItem: "Sun Wukong",
    description:"O rei macaco",
    value: "Guerreiro",
    addCart: "Adicionar ao carrinho",
    class: "./img/icons/guerreiro.png",
    type: "Físico",
  },
  {
    id: 12,
    img: "./img/Gods/Loki.png",
    nameItem: "Loki",
    description:
      "O deus trapaceiro",
    value: "Assassino",
    addCart: "Corporal",
    class: "./img/icons/assassino.png",
    type: "Físico",
  },
  {
    id: 13,
    img: "./img/Gods/janus.png",
    nameItem: "Janus",
    description:
      "O Deus dos Portais e Passagens",
    value: "Mago",
    addCart: "Atirador",
    class: "./img/icons/mago.png",
    type: "Mágico",
  },
  {
    id: 14,
    img: "./img/Gods/poseidon.png",
    nameItem: "Poseidon",
    description:
      "Deus dos oceanos",
    value: "Mago",
    addCart: "Atirador",
    class: "./img/icons/mago.png",
    type: "Mágico",
  },
  {
    id: 15,
    img: "./img/Gods/barao samedi.png",
    nameItem: "Barão Samedi",
    description:
      "Deus da vida e da morte",
    value: "Mago",
    addCart: "Atirador",
    class: "./img/icons/mago.png",
    type: "Mágico",
  },
  {
    id: 16,
    img: "./img/Gods/hou yi.png",
    nameItem: "Hou Yi",
    description:
      "Defensor da Terra",
    value: "Caçador",
    addCart: "Atirador",
    class: "./img/icons/caçador.png",
    type: "Físico",
  },
  {
    id: 17,
    img: "./img/Gods/ah puch.png",
    nameItem: "Ah Puch",
    description:
      "Deus da Decadência",
    value: "Mago",
    addCart: "Atirador",
    class: "./img/icons/mago.png",
    type: "Mágico",
  },
];
